language: java
jdk:
  - openjdk17
before_install:
  - cd Aphos-Engine
stages:
  - build
  - test
  -
# Cache Gradle dependencies to speed up builds
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: build
      script:
        - ./gradlew assemble   
    - stage: test
      script:
        - ./gradlew test   
